/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vizualizacao;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(int id,  String usuario, String senha, String tipo) {
        initComponents();
        lblUsuario.setText(usuario);
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnPaciente = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEnfermeira = new javax.swing.JButton();
        btnMedico = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miMedico = new javax.swing.JMenuItem();
        miPaciente = new javax.swing.JMenuItem();
        miUsuario = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Ajuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        btnPaciente.setBackground(new java.awt.Color(255, 255, 255));
        btnPaciente.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnPaciente.setForeground(new java.awt.Color(255, 102, 102));
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fracture.png"))); // NOI18N
        btnPaciente.setText("Pacientes    ");
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 290, 70));

        btnAgenda.setBackground(new java.awt.Color(255, 255, 255));
        btnAgenda.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnAgenda.setForeground(new java.awt.Color(255, 102, 102));
        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/notebook_78405.png"))); // NOI18N
        btnAgenda.setText("Agenda     ");
        btnAgenda.setToolTipText("");
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 290, 70));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Menu Principal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 260, -1));

        btnEnfermeira.setBackground(new java.awt.Color(255, 255, 255));
        btnEnfermeira.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnEnfermeira.setForeground(new java.awt.Color(255, 102, 102));
        btnEnfermeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/nurse.png"))); // NOI18N
        btnEnfermeira.setText("Enfermeiras");
        btnEnfermeira.setBorder(null);
        getContentPane().add(btnEnfermeira, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 290, 70));

        btnMedico.setBackground(new java.awt.Color(255, 255, 255));
        btnMedico.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnMedico.setForeground(new java.awt.Color(255, 102, 102));
        btnMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/doctor.png"))); // NOI18N
        btnMedico.setText("Médicos    ");
        btnMedico.setBorder(null);
        btnMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 290, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Logado em:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 20));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 320, 20));

        jMenu1.setText("Cadastrar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miMedico.setText("Médico");
        miMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(miMedico);

        miPaciente.setText("Paciente");
        miPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPacienteActionPerformed(evt);
            }
        });
        jMenu1.add(miPaciente);

        miUsuario.setText("Enfermeira");
        jMenu1.add(miUsuario);

        jMenuItem4.setText("Usuário");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatório");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ferramentas");
        jMenuBar1.add(jMenu3);

        Ajuda.setText("Ajuda");

        jMenuItem1.setText("Sobre");
        Ajuda.add(jMenuItem1);
        Ajuda.add(jSeparator1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Ajuda.add(jMenuItem2);

        jMenuBar1.add(Ajuda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1137, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMedicoActionPerformed
        new FormMedico().setVisible(true);
    }//GEN-LAST:event_miMedicoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       int i = JOptionPane.showConfirmDialog(this, "Deseja fechar o sistema?", "Atenção", JOptionPane.YES_NO_OPTION);
       if(i == JOptionPane.YES_OPTION){
        System.exit(0);
          
       }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicoActionPerformed
       new FormMedico().setVisible(true);
    }//GEN-LAST:event_btnMedicoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        new FormMedico().setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            new FormUsuario().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        new FormPaciente().setVisible(true);
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void miPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPacienteActionPerformed
         new FormPaciente().setVisible(true);
    }//GEN-LAST:event_miPacienteActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
         new FormAgenda().setVisible(true);
    }//GEN-LAST:event_btnAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ajuda;
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnEnfermeira;
    private javax.swing.JButton btnMedico;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem miMedico;
    private javax.swing.JMenuItem miPaciente;
    private javax.swing.JMenuItem miUsuario;
    // End of variables declaration//GEN-END:variables
}
